Publish version 1.4
Ubuntufanboy/bad-apple pull request #12
Opened 2023-04-07 23:36 UTC by Ubuntufanboy

The major changes are:

- insane syncing (MUCH better than before)
- a remote to control the video and audio of the program
- 10% faster load times

2023-04-07 23:40 UTC, Ubuntufanboy reviewed
Add if opener to the player when we need to make our frames

2023-04-07 23:56 UTC, Debianfanboy requested changes
Overall, a lot of junk code. Try to remove variables. A lot of pointless code with little readability. It's important to add more comments so more people can work on the codebase

2023-04-07 23:56 UTC, Debianfanboy commented on main.py
> +    for i in range(1, 3284):
Should be for i in range(1,3286)

2023-04-07 23:56 UTC, Debianfanboy commented on main.py
>          print("Already exists")
What exists? Should mention how this is for pre-processed files

2023-04-07 23:56 UTC, Debianfanboy commented on main.py
>      print("Directory does not exist")
What directory does not exist?

2023-04-07 23:56 UTC, Debianfanboy commented on main.py
> +
add ``if opener:`` here

2023-04-07 23:56 UTC, Debianfanboy commented on main.py
>  import numpy as np
just in general we need more helpful comments. Add 5 more block comments and 10 more inline comments. Make sure they are actually useful

2023-04-07 23:56 UTC, Debianfanboy commented on main.py
> +print("Are you using GNOME? y/n If you don't know enter n")
Change to "If you don't know click y"

2023-04-07 23:56 UTC, Debianfanboy commented on main.py
> +if answer == "y":
change to is ``if answer != "n"``

2023-04-07 23:56 UTC, Debianfanboy commented on main.py
>          print("Already exists")
Perhaps also say "x folder has all y amount of files"

2023-04-07 23:56 UTC, Debianfanboy commented on main.py
>          filename = str(i) + ".txt"
This is pointless... Just change to ``with open(f"{i}.txt"):``

2023-04-07 23:56 UTC, Debianfanboy commented on main.py
>              frame = f.read()
This is pointless just do ``frames.append(f.read())``

2023-04-08 00:22 UTC, Ubuntufanboy commented
FIXED. Committing to main directly

2023-04-08 00:22 UTC, closed without merging